packages:
  - "packages/*"

catalog:
  tshy: ^3.0.2
  typescript: ^5.5.4
  vitest: ^3.1.2
  eslint: ^9.9.0
  "@testing-library/jest-dom": ^6.4.8
  playwright: ^1.46.0
  "@vitest/browser": ^3.1.2
  "@vitest/coverage-istanbul": ^3.1.2
  "@vitest/coverage-v8": ^3.1.2
